# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Idu Mattu Adu
email: iduadu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Idu Mattu Adu publishes blogs, poems, short stories on culture, travels, current affairs, techonology and security
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://idumattuadu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: idumattuadu
github_username:  idumattuadu
linkedin_username: gopalvkulkarni

#Google Analytics
google_analytics_id: G-5LJ5Z80S24

# Build settings
#theme: minima
plugins:
  - jekyll-feed

name: Idu Mattu Adu
permalink: /:title

include:
  - _pages

defaults:
  - 
    scope:
      path : ""
      type: "pages"
    values:
      layout: page
  -  
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Gopal Kulkarni"

collections:
  kannada:
    output: true
  poems:
    output: true



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
